#!/bin/sh

export OPENAI_API_KEY=$($(dirname $0)/openai-password.gitignored)
export ANTHROPIC_API_KEY=$($(dirname $0)/anthropic-password.gitignored)

curl -s https://api.openai.com/v1/models -H "Authorization: Bearer $OPENAI_API_KEY" | jq -r '.data | map(["openai", (.created | todateiso8601), .id]) as $rows | ["vendor", "created", "id"], $rows[] | @csv'
curl -s https://api.anthropic.com/v1/models -H "anthropic-version: 2023-06-01" -H "x-api-key: $ANTHROPIC_API_KEY" | jq -r '.data | map(["anthropic", .created_at, .id])[] | @csv'
